# original, full query
{"operationName":"SearchEmotes","variables":{"query":"","limit":300,"page":1,"sort":{"value":"popularity","order":"DESCENDING"},"filter":{"category":"TOP","exact_match":false,"case_sensitive":false,"ignore_tags":false,"zero_width":false,"animated":false,"aspect_ratio":""}},"query":"query SearchEmotes($query: String!, $page: Int, $sort: Sort, $limit: Int, $filter: EmoteSearchFilter) {\n  emotes(query: $query, page: $page, sort: $sort, limit: $limit, filter: $filter) {\n    count\n    items {\n      id\n      name\n      state\n      trending\n      owner {\n        id\n        username\n        display_name\n        style {\n          color\n          paint_id\n          __typename\n        }\n        __typename\n      }\n      flags\n      host {\n        url\n        files {\n          name\n          format\n          width\n          height\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}"}

# query only for the 4 attributes that my api wrapper uses
"query":"query SearchEmotes($query: String!, $page: Int, $sort: Sort, $limit: Int, $filter: EmoteSearchFilter) {\n emotes(query: $query, page: $page, sort: $sort, limit: $limit, filter: $filter) {\nitems{\n id\n name\n owner{\n username\n }\n host{\n url}}\n}\n}"}

# query for only emote urls # optimal limit: 100
"query":"query SearchEmotes($query: String!, $page: Int, $sort: Sort, $limit: Int, $filter: EmoteSearchFilter) {\n emotes(query: $query, page: $page, sort: $sort, limit: $limit, filter: $filter) {\nitems{host{\n url}}\n}\n}"}

# maximum amount of emotes go get from search results: 300
# this also applies, even if the limit is set higher than that
# same for pages with a maximum of 25
# High amounts of data requested can often result in CursorNotFound errors